const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.NSG_Inventory,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Multiplayer,
		C3.Behaviors.solid,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Behaviors.bound,
		C3.Plugins.List,
		C3.Plugins.Button,
		C3.Behaviors.Bullet,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Turret,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.ScriptsInEvents.Game_event_sheet_Event94_Act3,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.TiledBg.Acts.SetEffectEnabled,
		C3.Plugins.TiledBg.Acts.AddInstanceVar,
		C3.ScriptsInEvents.Game_event_sheet_Event461_Act1,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.ScriptsInEvents.Game_event_sheet_Event488_Act1,
		C3.Plugins.NSG_Inventory.Acts.MoveAllItems,
		C3.Plugins.List.Cnds.OnSelectionChanged,
		C3.Plugins.List.Exps.SelectedText,
		C3.ScriptsInEvents.Game_event_sheet_Event532_Act2,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.List.Cnds.CompareInstanceVar,
		C3.ScriptsInEvents.Game_event_sheet_Event537_Act3,
		C3.ScriptsInEvents.Game_event_sheet_Event548_Act3,
		C3.ScriptsInEvents.Game_event_sheet_Event548_Act5,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.List.Acts.SetVisible,
		C3.ScriptsInEvents.Game_event_sheet_Event553_Act1,
		C3.Plugins.List.Acts.Select,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.random,
		C3.ScriptsInEvents.Game_event_sheet_Event568_Act3,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.ScriptsInEvents.Game_event_sheet_Event633_Act2,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.NSG_Inventory.Acts.CreateItem,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.NSG_Inventory.Cnds.IsInventoryShown,
		C3.Plugins.NSG_Inventory.Acts.HideInventory,
		C3.Plugins.NSG_Inventory.Acts.ShowInventory,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.ScriptsInEvents.Game_event_sheet_Event839_Act2,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Behaviors.Turret.Cnds.HasTarget,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.LoadState,
		C3.ScriptsInEvents.Smelter_event_sheet_Event2_Act3,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.NSG_Inventory.Acts.SetItemQuantity,
		C3.Plugins.NSG_Inventory.Exps.ItemQuantity,
		C3.ScriptsInEvents.Smelter_event_sheet_Event13_Act3,
		C3.ScriptsInEvents.Smelter_event_sheet_Event13_Act5,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.NSG_Inventory.Exps.ItemIdBySlotId,
		C3.Plugins.NSG_Inventory.Exps.ItemType,
		C3.ScriptsInEvents.Smelter_event_sheet_Event20_Act4,
		C3.ScriptsInEvents.Smelter_event_sheet_Event20_Act5,
		C3.Plugins.List.Cnds.CompareSelectedText,
		C3.ScriptsInEvents.Smelter_event_sheet_Event22_Act1,
		C3.ScriptsInEvents.Smelter_event_sheet_Event23_Act5
	];
};
self.C3_JsPropNameTable = [
	{Pin: 0},
	{Dust_Animation_Down: 0},
	{DIR: 0},
	{ANIM: 0},
	{DIR_NUMBER: 0},
	{Miner_Animations: 0},
	{Miner_Base: 0},
	{Dust_Animation_Right: 0},
	{Dust_Animation_Left: 0},
	{UP: 0},
	{DOWN: 0},
	{LEFT: 0},
	{RIGHT: 0},
	{DRILL: 0},
	{IDLE: 0},
	{HP: 0},
	{Max_HP: 0},
	{Energy: 0},
	{Max_Energy: 0},
	{Money: 0},
	{Fall_Timer: 0},
	{DMG: 0},
	{Laser_Gun: 0},
	{Coal: 0},
	{Quartz: 0},
	{Bauxite: 0},
	{Iron: 0},
	{Chromium: 0},
	{Copper: 0},
	{Lithium: 0},
	{Silver: 0},
	{Nickel: 0},
	{Zinc: 0},
	{Gold: 0},
	{Diamond: 0},
	{Dynamite: 0},
	{Battery: 0},
	{Repair_Kit: 0},
	{Teleporter: 0},
	{Weight: 0},
	{Laser_Gun_Active: 0},
	{Shield_Heat: 0},
	{Shield_Impact: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Miner_Box: 0},
	{Miner_Drill_Damage: 0},
	{Active: 0},
	{Down: 0},
	{Right: 0},
	{Left: 0},
	{Miner_Drill: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Explosion_Damage: 0},
	{Explosion_Area: 0},
	{Inventory: 0},
	{Amount_Due: 0},
	{Shop_Cart_Object: 0},
	{SpriteFont: 0},
	{Silicon: 0},
	{Aluminium_Ingot: 0},
	{Iron_Ingot: 0},
	{Chromium_Ingot: 0},
	{Copper_Ingot: 0},
	{Lithium_Ingot: 0},
	{Silver_Ingot: 0},
	{Nickel_Ingot: 0},
	{Zinc_Ingot: 0},
	{Gold_Ingot: 0},
	{Global_Inventory_Object: 0},
	{LocalStorage: 0},
	{Multiplayer: 0},
	{Value: 0},
	{Warehouse_Sell_Cart_Object: 0},
	{Explosion_Anim: 0},
	{Solid: 0},
	{Game_Concrete_Block: 0},
	{Hp: 0},
	{MaxHp: 0},
	{animationNumber: 0},
	{Explodes: 0},
	{Dirt_Block_Top: 0},
	{Game_Wall_Block: 0},
	{Bauxite_Block: 0},
	{Coal_Block: 0},
	{Dirt_Block: 0},
	{Quartz_Block: 0},
	{Coal_Block_2: 0},
	{Dirt_Block_2: 0},
	{Iron_Block: 0},
	{Chromium_Block: 0},
	{Copper_Block: 0},
	{Lithium_Block: 0},
	{Silver_Block: 0},
	{Gold_Block: 0},
	{Nickel_Block: 0},
	{Zinc_Block: 0},
	{Diamond_Block: 0},
	{Stone_Block: 0},
	{Lava_Block: 0},
	{Quartz_Inv_Sprite: 0},
	{Coal_Inv_Sprite: 0},
	{Bauxite_Ore_Inv_Sprite: 0},
	{Dynamite_Inv_Sprite: 0},
	{Aluminium_Ingot_Inv_Sprite: 0},
	{Teleporter_Inv_Sprite: 0},
	{Battery_Inv_Sprite: 0},
	{Repair_Kit_Inv_Sprite: 0},
	{Iron_Inv_Sprite: 0},
	{Chromium_Inv_Sprite: 0},
	{Copper_Inv_Sprite: 0},
	{Lithium_Inv_Sprite: 0},
	{Silver_Inv_Sprite: 0},
	{Nickel_Inv_Sprite: 0},
	{Zinc_Inv_Sprite: 0},
	{Gold_Inv_Sprite: 0},
	{Diamond_Inv_Sprite: 0},
	{DragDrop: 0},
	{Bauxite_Ore: 0},
	{Iron_Ore: 0},
	{Chromium_Ore: 0},
	{Copper_Ore: 0},
	{Lithium_Ore: 0},
	{Silver_Ore: 0},
	{Nickel_Ore: 0},
	{Zinc_Ore: 0},
	{Gold_Ore: 0},
	{Consumables_Slot_Art: 0},
	{Consumables_Text: 0},
	{BoundToLayout: 0},
	{HUD_Main: 0},
	{minerInventory_Slot_Art: 0},
	{Value_Weight_Text: 0},
	{Inventory_text: 0},
	{GlobalInventory_Slot_Art: 0},
	{Smelter_Slot_Art: 0},
	{Money_Text: 0},
	{Energy_text: 0},
	{Energy_Level_Text: 0},
	{HP_Level_Text: 0},
	{HP_text: 0},
	{Energy_Background: 0},
	{Energy_Bar: 0},
	{HP_Background: 0},
	{HP_Bar: 0},
	{Inventory_Global_Text: 0},
	{Dynamite_Q: 0},
	{Repair_Kit_Q: 0},
	{Battery_Q: 0},
	{Teleporter_Q: 0},
	{HUD_Weight_Text: 0},
	{HUD_Height_Text: 0},
	{Reload_Bar: 0},
	{Charge_Bar: 0},
	{Add_To_Cart_Background_Battery: 0},
	{Add_To_Cart_Background_Dynamite: 0},
	{Add_To_Cart_Background_Repair_Kit: 0},
	{Add_To_Cart_Background_Teleporter: 0},
	{Add_To_Cart_Battery_Text: 0},
	{Add_To_Cart_Dynamite_Text: 0},
	{Add_To_Cart_Repair_Kit_Text: 0},
	{Add_To_Cart_Teleporter_Text: 0},
	{Shop_Amount_Due_Text: 0},
	{Shop_Background: 0},
	{Shop_Buy_Button: 0},
	{Shop_Reset_Button: 0},
	{Shopping_List_Text: 0},
	{ID: 0},
	{Smelter_Add_Amount: 0},
	{Smelter_Background: 0},
	{Smelter_Clock: 0},
	{Smelter_Crafting_Amount_Background: 0},
	{Smelter_Crafting_Amount_Text: 0},
	{Smelter_Crafting_Button: 0},
	{Max_Amount: 0},
	{Busy: 0},
	{Crafting_Amount: 0},
	{Crafting_Time: 0},
	{Furnace_Active: 0},
	{Smelt_Next_Item: 0},
	{Timer_Second_Has_Passed: 0},
	{Smelter_Furnace_1_Object: 0},
	{Smelter_Max_Amount: 0},
	{Smelter_recipe_List: 0},
	{Smelter_Recipe_Text: 0},
	{Smelter_Req_Item_Background: 0},
	{Smelter_Req_Items_Text: 0},
	{Smelter_Subtract_Amount: 0},
	{Furnace_1_Sprite: 0},
	{Aluminium_Ingot_Crate: 0},
	{Bauxite_Crate: 0},
	{Chromium_Crate: 0},
	{Chromium_Ingot_Crate: 0},
	{Coal_Crate: 0},
	{Copper_Crate: 0},
	{Copper_Ingot_Crate: 0},
	{Diamond_Crate: 0},
	{Gold_Crate: 0},
	{Gold_Ingot_Crate: 0},
	{Iron_Crate: 0},
	{Iron_Ingot_Crate: 0},
	{Lithium_Crate: 0},
	{Lithium_Ingot_Crate: 0},
	{Nickel_Crate: 0},
	{Nickel_Ingot_Crate: 0},
	{Quartz_Crate: 0},
	{Silicon_Crate: 0},
	{Silver_Crate: 0},
	{Silver_Ingot_Crate: 0},
	{Zinc_Crate: 0},
	{Zinc_Ingot_Crate: 0},
	{Move_All_To_Warehouse: 0},
	{Warehouse_Background: 0},
	{Sell_Bauxite_Button_Global_Inventory: 0},
	{Sell_Coal_Button_Global_Inventory: 0},
	{Sell_Quartz_Button_Global_Inventory: 0},
	{Global_Inventory_Bauxite_Text: 0},
	{Global_Inventory_Coal_Text: 0},
	{Global_Inventory_Quartz_Text: 0},
	{Global_Inventory_Aluminium_Ingot_Text: 0},
	{Global_Inventory_Iron_Text: 0},
	{Global_Inventory_Chromium_Text: 0},
	{Global_Inventory_Copper_Text: 0},
	{Global_Inventory_Lithium_Text: 0},
	{Global_Inventory_Silver_Text: 0},
	{Global_Inventory_Nickel_Text: 0},
	{Global_Inventory_Zinc_Text: 0},
	{Global_Inventory_Gold_Text: 0},
	{Global_Inventory_Diamond_Text: 0},
	{Sell_Iron_Button_Global_Inventory: 0},
	{Sell_Chromium_Button_Global_Inventory: 0},
	{Sell_Copper_Button_Global_Inventory: 0},
	{Sell_Lithium_Button_Global_Inventory: 0},
	{Sell_Silver_Button_Global_Inventory: 0},
	{Sell_Nickel_Button_Global_Inventory: 0},
	{Sell_Zinc_Button_Global_Inventory: 0},
	{Sell_Gold_Button_Global_Inventory: 0},
	{Sell_Diamond_Button_Global_Inventory: 0},
	{Global_Inventory_Silicon_Text: 0},
	{Global_Inventory_Iron_Ingot_Text: 0},
	{Global_Inventory_Chromium_Ingot_Text: 0},
	{Global_Inventory_Copper_Ingot_Text: 0},
	{Global_Inventory_Lithium_Ingot_Text: 0},
	{Global_Inventory_Silver_Ingot_Text: 0},
	{Global_Inventory_Nickel_Ingot_Text: 0},
	{Global_Inventory_Zinc_Ingot_Text: 0},
	{Global_Inventory_Gold_Ingot_Text: 0},
	{Sell_Silicon_Button_Global_Inventory: 0},
	{Sell_Aluminium_Ingot_Button_Global_Inventory: 0},
	{Sell_Iron_Ingot_Button_Global_Inventory: 0},
	{Sell_Chromium_Ingot_Button_Global_Inventory: 0},
	{Sell_Copper_Ingot_Button_Global_Inventory: 0},
	{Sell_Lithium_Ingot_Button_Global_Inventory: 0},
	{Sell_Silver_Ingot_Button_Global_Inventory: 0},
	{Sell_Nickel_Ingot_Button_Global_Inventory: 0},
	{Sell_Zinc_Ingot_Button_Global_Inventory: 0},
	{Sell_Gold_Ingot_Button_Global_Inventory: 0},
	{Warehouse_Deposit_Background: 0},
	{Enter_Shop_Text: 0},
	{Enter_Smelter_Text: 0},
	{Enter_Warehouse_Text: 0},
	{Shop_Door: 0},
	{Warehouse_Door: 0},
	{Smelter_Door: 0},
	{Shop_Building_art: 0},
	{Smelter_Building_Art: 0},
	{Warehouse_Building_Art: 0},
	{Game_Sky_Background: 0},
	{TestText: 0},
	{Credit_Card_Background: 0},
	{Bullet: 0},
	{Bullet_Sprite: 0},
	{Direction: 0},
	{Charge: 0},
	{Max_Charge: 0},
	{Reload: 0},
	{Reload_Time: 0},
	{MoveTo: 0},
	{Devil_Boss_Sprite: 0},
	{Wall: 0},
	{Turret: 0},
	{Devil_Boss_Pentagram: 0},
	{Devil_Bullet_Sprite: 0},
	{Drill_Upg: 0},
	{Energy_Upg: 0},
	{Passive_Upg: 0},
	{Engine_Upg: 0},
	{Shield_Upg: 0},
	{Meta_Upg_Background: 0},
	{Meta_ScrollabeSprite: 0},
	{Scroll_TOP: 0},
	{Scroll_BOTTOM: 0},
	{Focused: 0},
	{Focus: 0},
	{Meta_Drill_DMG_T1_Button: 0},
	{Meta_Drill_DMG_T2_Button: 0},
	{Damage_Tier_1_Level: 0},
	{Damage_Tier_1_Completed: 0},
	{Damage_Tier_2_Level: 0},
	{Damage_Tier_2_Completed: 0},
	{Damage_Tier_3_Level: 0},
	{Damage_Tier_3_Completed: 0},
	{Damage_Tier_4_Level: 0},
	{Damage_Tier_4_Completed: 0},
	{Damage_Tier_5_Level: 0},
	{Damage_Tier_5_Completed: 0},
	{Base_Damage_Tier_1_Level: 0},
	{Base_Damage_Tier_1_Completed: 0},
	{Base_Damage_Tier_2_Level: 0},
	{Base_Damage_Tier_2_Completed: 0},
	{Base_Damage_Tier_3_Level: 0},
	{Base_Damage_Tier_3_Completed: 0},
	{Base_Damage_Tier_4_Level: 0},
	{Base_Damage_Tier_4_Completed: 0},
	{Base_Damage_Tier_5_Level: 0},
	{Base_Damage_Tier_5_Completed: 0},
	{Meta_Drill_Upg_Button: 0},
	{Meta_Upg_Text: 0},
	{Meta_Upgrade_button: 0},
	{Energy_Max_Tier_1_Level: 0},
	{Energy_Max_Tier_1_Completed: 0},
	{Energy_Max_Tier_2_Level: 0},
	{Energy_Max_Tier_2_Completed: 0},
	{Energy_Max_Tier_3_Level: 0},
	{Energy_Max_Tier_3_Completed: 0},
	{Energy_Effi_Tier_1_Level: 0},
	{Energy_Effi_Tier_1_Completed: 0},
	{Energy_Effi_Tier_2_Level: 0},
	{Energy_Effi_Tier_2_Completed: 0},
	{Energy_Effi_Tier_3_Level: 0},
	{Energy_Effi_Tier_3_Completed: 0},
	{Energy_Regen_Tier_1_Level: 0},
	{Energy_Regen_Tier_1_Completed: 0},
	{Energy_Regen_Tier_2_Level: 0},
	{Energy_Regen_Tier_2_Completed: 0},
	{Energy_Regen_Tier_3_Level: 0},
	{Energy_Regen_Tier_3_Completed: 0},
	{Meta_Energy_Upg_Button: 0},
	{Meta_Energy_Max_T1_Button: 0},
	{Meta_Req_Item_Text: 0},
	{Meta_Max_Level_Text: 0},
	{Meta_Current_Level_Text: 0},
	{Meta_Stats_Text: 0},
	{Test_Furnace_Text: 0},
	{Coal_Meta: 0},
	{DMG_Multiplier_1: 0},
	{Energy_Effi_Multiplier_1: 0},
	{Energy_Regen_Multiplier: 0},
	{Meta_Multiplier_Object: 0},
	{Meta_Drill_DMG_T3_Button: 0},
	{Meta_Drill_DMG_T4_Button: 0},
	{Meta_Drill_DMG_T5_Button: 0},
	{Meta_Drill_DMG_Multiplier_Background: 0},
	{Meta_Drill_DMG_BASE_Background: 0},
	{Meta_Drill_BASE_DMG_T1_Button: 0},
	{Meta_Drill_BASE_DMG_T2_Button: 0},
	{Meta_Drill_BASE_DMG_T3_Button: 0},
	{Meta_Drill_BASE_DMG_T4_Button: 0},
	{Meta_Drill_BASE_DMG_T5_Button: 0},
	{Quest_1_Active: 0},
	{Quest_1_Completed: 0},
	{Quest_2_Active: 0},
	{Quest_2_Completed: 0},
	{Quest_3_Active: 0},
	{Quest_3_Completed: 0},
	{Quest_4_Active: 0},
	{Quest_4_Completed: 0},
	{Quest_5_Active: 0},
	{Quest_5_Completed: 0},
	{Quest_6_Active: 0},
	{Quest_6_Completed: 0},
	{Quest_7_Active: 0},
	{Quest_7_Completed: 0},
	{Quest_8_Active: 0},
	{Quest_8_Completed: 0},
	{Quest_9_Active: 0},
	{Quest_9_Completed: 0},
	{Quest_10_Active: 0},
	{Quest_10_Completed: 0},
	{Claim_Button: 0},
	{Quartz_Meta: 0},
	{Bauxite_Meta: 0},
	{Iron_Meta: 0},
	{Chromium_Meta: 0},
	{Copper_Meta: 0},
	{Lithium_Meta: 0},
	{Silver_Meta: 0},
	{Nickel_Meta: 0},
	{Zinc_Meta: 0},
	{Gold_Meta: 0},
	{Diamond_Meta: 0},
	{Silicone_Meta: 0},
	{Aluminium_Ingot_Meta: 0},
	{Iron_Ingot_Meta: 0},
	{Chromium_Ingot_Meta: 0},
	{Copper_Ingot_Meta: 0},
	{Lithium_Ingot_Meta: 0},
	{Silver_Ingot_Meta: 0},
	{Nickel_Ingot_Meta: 0},
	{Zinc_Ingot_Meta: 0},
	{Gold_Ingot_Meta: 0},
	{Meta_Energy_Max_T2_Button: 0},
	{Meta_Energy_Max_T3_Button: 0},
	{Meta_Energy_Max_Background: 0},
	{Meta_Energy_Efficiency_Background: 0},
	{Meta_Energy_Efficiency_T1_Button: 0},
	{Meta_Energy_Efficiency_T2_Button: 0},
	{Meta_Energy_Efficiency_T3_Button: 0},
	{Meta_Energy_Regen_Background: 0},
	{Meta_Energy_Regeneration_T1_Button: 0},
	{Meta_Energy_Regeneration_T2_Button: 0},
	{Meta_Energy_Regeneration_T3_Button: 0},
	{Meta_Passive_Coal: 0},
	{Meta_Passive_Bauxite: 0},
	{Meta_Passive_Quartz: 0},
	{Meta_Passive_Iron: 0},
	{Meta_Passive_Chromium: 0},
	{Meta_Passive_Copper: 0},
	{Meta_Passive_Income_Object: 0},
	{Passive_Coal_Level: 0},
	{Passive_Coal_Completed: 0},
	{Passive_Quartz_Level: 0},
	{Passive_Quartz_Completed: 0},
	{Passive_Bauxite_Level: 0},
	{Passive_Bauxite_Completed: 0},
	{Passive_Iron_Level: 0},
	{Passive_Iron_Completed: 0},
	{Passive_Chromium_Level: 0},
	{Passive_Chromium_Completed: 0},
	{Passive_Copper_Level: 0},
	{Passive_Copper_Completed: 0},
	{Meta_Passive_Upg_Button: 0},
	{Meta_Passive_Coal_Button: 0},
	{Meta_Passive_Quartz_Button: 0},
	{Meta_Passive_Bauxite_Button: 0},
	{Money_Meta: 0},
	{Passive_Income_Background: 0},
	{Meta_Passive_Income_Text: 0},
	{Meta_Stats_Button: 0},
	{Meta_Passive_Button: 0},
	{HUD_Grey: 0},
	{HUD_Global_Inventory_Button: 0},
	{HUD_Miner_Inventory_Button: 0},
	{Miner_Inventory_Background_Black: 0},
	{Miner_Inventory_Text: 0},
	{Global_Inventory_Background_Black: 0},
	{HUD_Global_Inventory_Text: 0},
	{Warehouse_Sell_Cart_Background: 0},
	{Warehouse_Sell_Cart_Text: 0},
	{Warehouse_Deposit_Button: 0},
	{Warehouse_Sell_Button: 0},
	{Sell_Items_Button_Warehouse: 0},
	{Reset_Items_Button_Warehouse: 0},
	{Warehouse_Value_Text: 0},
	{Warehouse_Shelf_Sprite: 0},
	{SFX: 0},
	{Warehouse_Q_Background: 0},
	{HUD_Quest_Button: 0},
	{HUD_Menu_Button: 0},
	{HUD_Quest_Background: 0},
	{Quest_Text: 0},
	{Reward_Text: 0},
	{Game_Boundary_Sprite: 0},
	{Game_Upper_Boundary: 0},
	{Menu_Play_Button: 0},
	{HUD_Menu_Background: 0},
	{Main_Menu_Button: 0},
	{Settings_Menu_Button: 0},
	{Settings_Menu: 0},
	{Sound_Settings_Button: 0},
	{Mute_Button: 0},
	{Death_Screen: 0},
	{Death_Keep_Inventory_Button: 0},
	{Death_Dump_Inventory_Button2: 0},
	{Shop_Explainer_Background: 0},
	{Shop_Explainer_Text: 0},
	{Welcome_Triggered: 0},
	{Shopkeeper_Sprite: 0},
	{Item_Pick_Up_Text: 0},
	{Warning_Text_Miner: 0},
	{Sphere_Bullet_Sprite: 0},
	{HUD_Upgrades_Button: 0},
	{HUD_Money_Button: 0},
	{HUD_Stats_Background_Black: 0},
	{HUD_Stats_Text: 0},
	{HUD_Credit_Card_Background: 0},
	{Mitch: 0},
	{Hell_Background: 0},
	{Enemy_Turret_1: 0},
	{Enemy_Body: 0},
	{Enemy_Turret_2: 0},
	{Enemy_Body2: 0},
	{HUD_Enemy_1_HP_Background: 0},
	{HUD_Enemy_1_HP_Bar: 0},
	{HUD_Enemy_2_HP_Background: 0},
	{HUD_Enemy_2_HP_Bar: 0},
	{HUD_Enemy_1_HP_Text: 0},
	{HUD_Enemy_2_HP_Text: 0},
	{HUD_Devil_HP_Background2: 0},
	{HUD_Devil_HP_Bar: 0},
	{HUD_Devil_HP_Text: 0},
	{Devil_Fire_Ring: 0},
	{Mitch_Talk_Bubble: 0},
	{HUD_Locked: 0},
	{Gun_Crate: 0},
	{Buy_Gun_Button: 0},
	{Meta_Passive_Iron_Button: 0},
	{Meta_Passive_Chromium_Button: 0},
	{Meta_Passive_Copper_Button: 0},
	{Render_Object: 0},
	{Shop_Money_Text: 0},
	{Engine_Effect_Tier1_Level: 0},
	{Engine_Effect_Tier1_Completed: 0},
	{Engine_Effiency_Tier1_Level: 0},
	{Engine_Effiency_Tier1_Completed: 0},
	{Meta_Engine_Upg_Button: 0},
	{Meta_Engine_Effect_T1_Button: 0},
	{Meta_Engine_Effect_Background: 0},
	{Meta_Engine_Efficiency_Background: 0},
	{Meta_Engine_Efficiency_T1_Button: 0},
	{Shield_Impact_Tier1_Level: 0},
	{Shield_Impact_Tier1_Completed: 0},
	{Shield_Heat_Tier1_Level: 0},
	{Shield_Heat_Tier1_Completed: 0},
	{Meta_Shield_Upg_Button: 0},
	{Meta_Shield_Impact_Background: 0},
	{Meta_Shield_Impact_T1_Button: 0},
	{Meta_Shield_Heat_Background: 0},
	{Meta_Shield_Heat_T1_Button: 0},
	{Enemy_Background_First: 0},
	{Furnace_1_Background: 0},
	{Furnace_1_Text: 0},
	{Furnace_1_Buttons: 0},
	{Enemies_Object: 0},
	{Meta_Drill_DMG_Buttons: 0},
	{Meta_Energy_Buttons: 0},
	{Meta_Passive_Buttons: 0},
	{Meta_All_Buttons: 0},
	{Meta_Materials: 0},
	{Meta_Engine_Buttons: 0},
	{Meta_Shield_Buttons: 0},
	{Sell_Items_Buttons: 0},
	{Global_Inventory_Items_Text: 0},
	{Deposit_Menu_Buttons: 0},
	{Sell_Menu_Buttons: 0},
	{Crates: 0},
	{HUD_Menu_Buttons: 0},
	{Settings_Menu_Buttons: 0},
	{Death_Screen_All: 0},
	{Dust_Animations: 0},
	{Add_To_Cart_Text: 0},
	{Mining_Blocks_Family: 0},
	{Inventory_Sprites: 0},
	{Global_Inventory_Text: 0},
	{Ores: 0},
	{minerInventoryValue: 0},
	{minerInventoryWeight: 0},
	{Energy_Bar_Original_Width: 0},
	{HP_Bar_Original_Width: 0},
	{Miner_Mining_DMG: 0},
	{Miner_Energy_Efficiency: 0},
	{Miner_Energy_Regeneration: 0},
	{Miner_Height: 0},
	{Test: 0},
	{Vector_Y_Speed_Up: 0},
	{Vector_Y_Speed_Down: 0},
	{Vertical_Speed_Multiplier: 0},
	{Engine_Efficiency_Multiplier: 0},
	{Quest_Objective_1: 0},
	{Quest_Objective_2: 0},
	{Quest_Objective_3: 0},
	{Miner_Inventory_HUD_TEXT: 0},
	{Global_Inventory_HUD_TEXT: 0},
	{Warehouse_Sell_Cart_String: 0},
	{Shop_Cart_String: 0},
	{Required_Item_Quantity: 0},
	{Max_Level: 0},
	{Current_Level: 0},
	{Shopping_List: 0},
	{Warehouse_Item_ID: 0},
	{Warehouse_Item_Type: 0},
	{Warehouse_Item_Quantity: 0},
	{isRecipeSelected: 0},
	{selectedRecipe: 0},
	{smelterId: 0},
	{smeltingTimePerItem: 0},
	{localSmelterId: 0},
	{localSelectedRecipe: 0},
	{recipeText: 0},
	{maxAmount: 0},
	{Y: 0},
	{X: 0},
	{Ore: 0},
	{StartY: 0},
	{EndY: 0},
	{Charge_Bar_Original_Width: 0},
	{Reload_Bar_Original_Width: 0},
	{Offset: 0},
	{Item_ID: 0},
	{Item_Type: 0},
	{Item_Quantity: 0},
	{Consumable_ID: 0},
	{Quest_Target_1: 0},
	{Quest_Target_2: 0},
	{Quest_Target_3: 0},
	{ClockToggle: 0},
	{CraftingTime: 0},
	{CraftingTimeRecipe: 0},
	{TotalRequiredCraftingItems: 0},
	{AvailableCraftingItems: 0},
	{RequiredCraftingItems: 0},
	{CraftingAmount: 0},
	{CraftingMaxAmount: 0},
	{CraftingItemType: 0},
	{Smelter_ItemID: 0},
	{Smelter_Item_Type: 0},
	{Global_Inv_ItemID: 0},
	{Global_Inv_Item_Type: 0},
	{Global_Inv_Item_Slot_ID: 0}
];

self.InstanceType = {
	Dust_Animation_Down: class extends self.ISpriteInstance {},
	Miner_Animations: class extends self.ISpriteInstance {},
	Miner_Base: class extends self.ISpriteInstance {},
	Dust_Animation_Right: class extends self.ISpriteInstance {},
	Dust_Animation_Left: class extends self.ISpriteInstance {},
	Miner_Box: class extends self.ISpriteInstance {},
	Miner_Drill: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Explosion_Area: class extends self.ISpriteInstance {},
	Inventory: class extends self.IInstance {},
	Shop_Cart_Object: class extends self.ITiledBackgroundInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Global_Inventory_Object: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Multiplayer: class extends self.IInstance {},
	Warehouse_Sell_Cart_Object: class extends self.ISpriteInstance {},
	Explosion_Anim: class extends self.ISpriteInstance {},
	Game_Concrete_Block: class extends self.ITiledBackgroundInstance {},
	Dirt_Block_Top: class extends self.ISpriteInstance {},
	Game_Wall_Block: class extends self.ITiledBackgroundInstance {},
	Bauxite_Block: class extends self.ISpriteInstance {},
	Coal_Block: class extends self.ISpriteInstance {},
	Dirt_Block: class extends self.ISpriteInstance {},
	Quartz_Block: class extends self.ISpriteInstance {},
	Coal_Block_2: class extends self.ISpriteInstance {},
	Dirt_Block_2: class extends self.ISpriteInstance {},
	Iron_Block: class extends self.ISpriteInstance {},
	Chromium_Block: class extends self.ISpriteInstance {},
	Copper_Block: class extends self.ISpriteInstance {},
	Lithium_Block: class extends self.ISpriteInstance {},
	Silver_Block: class extends self.ISpriteInstance {},
	Gold_Block: class extends self.ISpriteInstance {},
	Nickel_Block: class extends self.ISpriteInstance {},
	Zinc_Block: class extends self.ISpriteInstance {},
	Diamond_Block: class extends self.ISpriteInstance {},
	Stone_Block: class extends self.ISpriteInstance {},
	Lava_Block: class extends self.ISpriteInstance {},
	Quartz_Inv_Sprite: class extends self.ISpriteInstance {},
	Coal_Inv_Sprite: class extends self.ISpriteInstance {},
	Bauxite_Ore_Inv_Sprite: class extends self.ISpriteInstance {},
	Dynamite_Inv_Sprite: class extends self.ISpriteInstance {},
	Aluminium_Ingot_Inv_Sprite: class extends self.ISpriteInstance {},
	Teleporter_Inv_Sprite: class extends self.ISpriteInstance {},
	Battery_Inv_Sprite: class extends self.ISpriteInstance {},
	Repair_Kit_Inv_Sprite: class extends self.ISpriteInstance {},
	Iron_Inv_Sprite: class extends self.ISpriteInstance {},
	Chromium_Inv_Sprite: class extends self.ISpriteInstance {},
	Copper_Inv_Sprite: class extends self.ISpriteInstance {},
	Lithium_Inv_Sprite: class extends self.ISpriteInstance {},
	Silver_Inv_Sprite: class extends self.ISpriteInstance {},
	Nickel_Inv_Sprite: class extends self.ISpriteInstance {},
	Zinc_Inv_Sprite: class extends self.ISpriteInstance {},
	Gold_Inv_Sprite: class extends self.ISpriteInstance {},
	Diamond_Inv_Sprite: class extends self.ISpriteInstance {},
	Quartz: class extends self.ISpriteInstance {},
	Coal: class extends self.ISpriteInstance {},
	Bauxite_Ore: class extends self.ISpriteInstance {},
	Iron_Ore: class extends self.ISpriteInstance {},
	Chromium_Ore: class extends self.ISpriteInstance {},
	Copper_Ore: class extends self.ISpriteInstance {},
	Lithium_Ore: class extends self.ISpriteInstance {},
	Silver_Ore: class extends self.ISpriteInstance {},
	Nickel_Ore: class extends self.ISpriteInstance {},
	Zinc_Ore: class extends self.ISpriteInstance {},
	Gold_Ore: class extends self.ISpriteInstance {},
	Diamond: class extends self.ISpriteInstance {},
	Consumables_Slot_Art: class extends self.ISpriteInstance {},
	Consumables_Text: class extends self.ITextInstance {},
	HUD_Main: class extends self.ITiledBackgroundInstance {},
	minerInventory_Slot_Art: class extends self.ISpriteInstance {},
	Value_Weight_Text: class extends self.ITextInstance {},
	Inventory_text: class extends self.ITextInstance {},
	GlobalInventory_Slot_Art: class extends self.ISpriteInstance {},
	Smelter_Slot_Art: class extends self.ISpriteInstance {},
	Money_Text: class extends self.ITextInstance {},
	Energy_text: class extends self.ITextInstance {},
	Energy_Level_Text: class extends self.ITextInstance {},
	HP_Level_Text: class extends self.ITextInstance {},
	HP_text: class extends self.ITextInstance {},
	Energy_Background: class extends self.ITiledBackgroundInstance {},
	Energy_Bar: class extends self.ITiledBackgroundInstance {},
	HP_Background: class extends self.ITiledBackgroundInstance {},
	HP_Bar: class extends self.ITiledBackgroundInstance {},
	Inventory_Global_Text: class extends self.ITextInstance {},
	Dynamite_Q: class extends self.ITextInstance {},
	Repair_Kit_Q: class extends self.ITextInstance {},
	Battery_Q: class extends self.ITextInstance {},
	Teleporter_Q: class extends self.ITextInstance {},
	HUD_Weight_Text: class extends self.ITextInstance {},
	HUD_Height_Text: class extends self.ITextInstance {},
	Reload_Bar: class extends self.ITiledBackgroundInstance {},
	Charge_Bar: class extends self.ITiledBackgroundInstance {},
	Add_To_Cart_Background_Battery: class extends self.ITiledBackgroundInstance {},
	Add_To_Cart_Background_Dynamite: class extends self.ITiledBackgroundInstance {},
	Add_To_Cart_Background_Repair_Kit: class extends self.ITiledBackgroundInstance {},
	Add_To_Cart_Background_Teleporter: class extends self.ITiledBackgroundInstance {},
	Add_To_Cart_Battery_Text: class extends self.ITextInstance {},
	Add_To_Cart_Dynamite_Text: class extends self.ITextInstance {},
	Add_To_Cart_Repair_Kit_Text: class extends self.ITextInstance {},
	Add_To_Cart_Teleporter_Text: class extends self.ITextInstance {},
	Shop_Amount_Due_Text: class extends self.ITextInstance {},
	Shop_Background: class extends self.ITiledBackgroundInstance {},
	Shop_Buy_Button: class extends self.ITiledBackgroundInstance {},
	Shop_Reset_Button: class extends self.ITiledBackgroundInstance {},
	Shopping_List_Text: class extends self.ITextInstance {},
	Smelter_Add_Amount: class extends self.ITiledBackgroundInstance {},
	Smelter_Background: class extends self.ITiledBackgroundInstance {},
	Smelter_Clock: class extends self.ITextInstance {},
	Smelter_Crafting_Amount_Background: class extends self.ITiledBackgroundInstance {},
	Smelter_Crafting_Amount_Text: class extends self.ITextInstance {},
	Smelter_Crafting_Button: class extends self.ITiledBackgroundInstance {},
	Smelter_Furnace_1_Object: class extends self.ISpriteInstance {},
	Smelter_Max_Amount: class extends self.ITiledBackgroundInstance {},
	Smelter_recipe_List: class extends self.IListInstance {},
	Smelter_Recipe_Text: class extends self.ITextInstance {},
	Smelter_Req_Item_Background: class extends self.ITiledBackgroundInstance {},
	Smelter_Req_Items_Text: class extends self.ITextInstance {},
	Smelter_Subtract_Amount: class extends self.ITiledBackgroundInstance {},
	Furnace_1_Sprite: class extends self.ISpriteInstance {},
	Aluminium_Ingot_Crate: class extends self.ISpriteInstance {},
	Bauxite_Crate: class extends self.ISpriteInstance {},
	Chromium_Crate: class extends self.ISpriteInstance {},
	Chromium_Ingot_Crate: class extends self.ISpriteInstance {},
	Coal_Crate: class extends self.ISpriteInstance {},
	Copper_Crate: class extends self.ISpriteInstance {},
	Copper_Ingot_Crate: class extends self.ISpriteInstance {},
	Diamond_Crate: class extends self.ISpriteInstance {},
	Gold_Crate: class extends self.ISpriteInstance {},
	Gold_Ingot_Crate: class extends self.ISpriteInstance {},
	Iron_Crate: class extends self.ISpriteInstance {},
	Iron_Ingot_Crate: class extends self.ISpriteInstance {},
	Lithium_Crate: class extends self.ISpriteInstance {},
	Lithium_Ingot_Crate: class extends self.ISpriteInstance {},
	Nickel_Crate: class extends self.ISpriteInstance {},
	Nickel_Ingot_Crate: class extends self.ISpriteInstance {},
	Quartz_Crate: class extends self.ISpriteInstance {},
	Silicon_Crate: class extends self.ISpriteInstance {},
	Silver_Crate: class extends self.ISpriteInstance {},
	Silver_Ingot_Crate: class extends self.ISpriteInstance {},
	Zinc_Crate: class extends self.ISpriteInstance {},
	Zinc_Ingot_Crate: class extends self.ISpriteInstance {},
	Move_All_To_Warehouse: class extends self.IButtonInstance {},
	Warehouse_Background: class extends self.ITiledBackgroundInstance {},
	Sell_Bauxite_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Coal_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Quartz_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Global_Inventory_Bauxite_Text: class extends self.ITextInstance {},
	Global_Inventory_Coal_Text: class extends self.ITextInstance {},
	Global_Inventory_Quartz_Text: class extends self.ITextInstance {},
	Global_Inventory_Aluminium_Ingot_Text: class extends self.ITextInstance {},
	Global_Inventory_Iron_Text: class extends self.ITextInstance {},
	Global_Inventory_Chromium_Text: class extends self.ITextInstance {},
	Global_Inventory_Copper_Text: class extends self.ITextInstance {},
	Global_Inventory_Lithium_Text: class extends self.ITextInstance {},
	Global_Inventory_Silver_Text: class extends self.ITextInstance {},
	Global_Inventory_Nickel_Text: class extends self.ITextInstance {},
	Global_Inventory_Zinc_Text: class extends self.ITextInstance {},
	Global_Inventory_Gold_Text: class extends self.ITextInstance {},
	Global_Inventory_Diamond_Text: class extends self.ITextInstance {},
	Sell_Iron_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Chromium_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Copper_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Lithium_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Silver_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Nickel_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Zinc_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Gold_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Diamond_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Global_Inventory_Silicon_Text: class extends self.ITextInstance {},
	Global_Inventory_Iron_Ingot_Text: class extends self.ITextInstance {},
	Global_Inventory_Chromium_Ingot_Text: class extends self.ITextInstance {},
	Global_Inventory_Copper_Ingot_Text: class extends self.ITextInstance {},
	Global_Inventory_Lithium_Ingot_Text: class extends self.ITextInstance {},
	Global_Inventory_Silver_Ingot_Text: class extends self.ITextInstance {},
	Global_Inventory_Nickel_Ingot_Text: class extends self.ITextInstance {},
	Global_Inventory_Zinc_Ingot_Text: class extends self.ITextInstance {},
	Global_Inventory_Gold_Ingot_Text: class extends self.ITextInstance {},
	Sell_Silicon_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Aluminium_Ingot_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Iron_Ingot_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Chromium_Ingot_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Copper_Ingot_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Lithium_Ingot_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Silver_Ingot_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Nickel_Ingot_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Zinc_Ingot_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Sell_Gold_Ingot_Button_Global_Inventory: class extends self.ISpriteInstance {},
	Warehouse_Deposit_Background: class extends self.ITiledBackgroundInstance {},
	Enter_Shop_Text: class extends self.ITextInstance {},
	Enter_Smelter_Text: class extends self.ITextInstance {},
	Enter_Warehouse_Text: class extends self.ITextInstance {},
	Shop_Door: class extends self.ITiledBackgroundInstance {},
	Warehouse_Door: class extends self.ITiledBackgroundInstance {},
	Smelter_Door: class extends self.ITiledBackgroundInstance {},
	Shop_Building_art: class extends self.ITiledBackgroundInstance {},
	Smelter_Building_Art: class extends self.ITiledBackgroundInstance {},
	Warehouse_Building_Art: class extends self.ITiledBackgroundInstance {},
	Game_Sky_Background: class extends self.ITiledBackgroundInstance {},
	TestText: class extends self.ITextInstance {},
	Credit_Card_Background: class extends self.ITiledBackgroundInstance {},
	Bullet_Sprite: class extends self.ISpriteInstance {},
	Laser_Gun: class extends self.ISpriteInstance {},
	Devil_Boss_Sprite: class extends self.ISpriteInstance {},
	Wall: class extends self.ITiledBackgroundInstance {},
	Devil_Boss_Pentagram: class extends self.ISpriteInstance {},
	Devil_Bullet_Sprite: class extends self.ISpriteInstance {},
	Meta_Upg_Background: class extends self.ISpriteInstance {},
	Meta_ScrollabeSprite: class extends self.ISpriteInstance {},
	Scroll_TOP: class extends self.ITextInstance {},
	Scroll_BOTTOM: class extends self.ITextInstance {},
	Meta_Drill_DMG_T1_Button: class extends self.ISpriteInstance {},
	Meta_Drill_DMG_T2_Button: class extends self.ISpriteInstance {},
	Meta_Drill_Upg_Button: class extends self.ISpriteInstance {},
	Meta_Upg_Text: class extends self.ITextInstance {},
	Meta_Upgrade_button: class extends self.ISpriteInstance {},
	Meta_Energy_Upg_Button: class extends self.ISpriteInstance {},
	Meta_Energy_Max_T1_Button: class extends self.ISpriteInstance {},
	Meta_Req_Item_Text: class extends self.ITextInstance {},
	Meta_Max_Level_Text: class extends self.ITextInstance {},
	Meta_Current_Level_Text: class extends self.ITextInstance {},
	Meta_Stats_Text: class extends self.ITextInstance {},
	Test_Furnace_Text: class extends self.ITextInstance {},
	Coal_Meta: class extends self.ISpriteInstance {},
	Meta_Multiplier_Object: class extends self.ISpriteInstance {},
	Meta_Drill_DMG_T3_Button: class extends self.ISpriteInstance {},
	Meta_Drill_DMG_T4_Button: class extends self.ISpriteInstance {},
	Meta_Drill_DMG_T5_Button: class extends self.ISpriteInstance {},
	Meta_Drill_DMG_Multiplier_Background: class extends self.ISpriteInstance {},
	Meta_Drill_DMG_BASE_Background: class extends self.ISpriteInstance {},
	Meta_Drill_BASE_DMG_T1_Button: class extends self.ISpriteInstance {},
	Meta_Drill_BASE_DMG_T2_Button: class extends self.ISpriteInstance {},
	Meta_Drill_BASE_DMG_T3_Button: class extends self.ISpriteInstance {},
	Meta_Drill_BASE_DMG_T4_Button: class extends self.ISpriteInstance {},
	Meta_Drill_BASE_DMG_T5_Button: class extends self.ISpriteInstance {},
	Claim_Button: class extends self.ISpriteInstance {},
	Quartz_Meta: class extends self.ISpriteInstance {},
	Bauxite_Meta: class extends self.ISpriteInstance {},
	Iron_Meta: class extends self.ISpriteInstance {},
	Chromium_Meta: class extends self.ISpriteInstance {},
	Copper_Meta: class extends self.ISpriteInstance {},
	Lithium_Meta: class extends self.ISpriteInstance {},
	Silver_Meta: class extends self.ISpriteInstance {},
	Nickel_Meta: class extends self.ISpriteInstance {},
	Zinc_Meta: class extends self.ISpriteInstance {},
	Gold_Meta: class extends self.ISpriteInstance {},
	Diamond_Meta: class extends self.ISpriteInstance {},
	Silicone_Meta: class extends self.ISpriteInstance {},
	Aluminium_Ingot_Meta: class extends self.ISpriteInstance {},
	Iron_Ingot_Meta: class extends self.ISpriteInstance {},
	Chromium_Ingot_Meta: class extends self.ISpriteInstance {},
	Copper_Ingot_Meta: class extends self.ISpriteInstance {},
	Lithium_Ingot_Meta: class extends self.ISpriteInstance {},
	Silver_Ingot_Meta: class extends self.ISpriteInstance {},
	Nickel_Ingot_Meta: class extends self.ISpriteInstance {},
	Zinc_Ingot_Meta: class extends self.ISpriteInstance {},
	Gold_Ingot_Meta: class extends self.ISpriteInstance {},
	Meta_Energy_Max_T2_Button: class extends self.ISpriteInstance {},
	Meta_Energy_Max_T3_Button: class extends self.ISpriteInstance {},
	Meta_Energy_Max_Background: class extends self.ISpriteInstance {},
	Meta_Energy_Efficiency_Background: class extends self.ISpriteInstance {},
	Meta_Energy_Efficiency_T1_Button: class extends self.ISpriteInstance {},
	Meta_Energy_Efficiency_T2_Button: class extends self.ISpriteInstance {},
	Meta_Energy_Efficiency_T3_Button: class extends self.ISpriteInstance {},
	Meta_Energy_Regen_Background: class extends self.ISpriteInstance {},
	Meta_Energy_Regeneration_T1_Button: class extends self.ISpriteInstance {},
	Meta_Energy_Regeneration_T2_Button: class extends self.ISpriteInstance {},
	Meta_Energy_Regeneration_T3_Button: class extends self.ISpriteInstance {},
	Meta_Passive_Income_Object: class extends self.ISpriteInstance {},
	Meta_Passive_Upg_Button: class extends self.ISpriteInstance {},
	Meta_Passive_Coal_Button: class extends self.ISpriteInstance {},
	Meta_Passive_Quartz_Button: class extends self.ISpriteInstance {},
	Meta_Passive_Bauxite_Button: class extends self.ISpriteInstance {},
	Money_Meta: class extends self.ISpriteInstance {},
	Passive_Income_Background: class extends self.ISpriteInstance {},
	Meta_Passive_Income_Text: class extends self.ITextInstance {},
	Meta_Stats_Button: class extends self.ISpriteInstance {},
	Meta_Passive_Button: class extends self.ISpriteInstance {},
	HUD_Grey: class extends self.ISpriteInstance {},
	HUD_Global_Inventory_Button: class extends self.ISpriteInstance {},
	HUD_Miner_Inventory_Button: class extends self.ISpriteInstance {},
	Miner_Inventory_Background_Black: class extends self.ISpriteInstance {},
	Miner_Inventory_Text: class extends self.ITextInstance {},
	Global_Inventory_Background_Black: class extends self.ISpriteInstance {},
	HUD_Global_Inventory_Text: class extends self.ITextInstance {},
	Warehouse_Sell_Cart_Background: class extends self.ISpriteInstance {},
	Warehouse_Sell_Cart_Text: class extends self.ITextInstance {},
	Warehouse_Deposit_Button: class extends self.ISpriteInstance {},
	Warehouse_Sell_Button: class extends self.ISpriteInstance {},
	Sell_Items_Button_Warehouse: class extends self.ISpriteInstance {},
	Reset_Items_Button_Warehouse: class extends self.ISpriteInstance {},
	Warehouse_Value_Text: class extends self.ITextInstance {},
	Warehouse_Shelf_Sprite: class extends self.ISpriteInstance {},
	SFX: class extends self.IInstance {},
	Warehouse_Q_Background: class extends self.ISpriteInstance {},
	HUD_Quest_Button: class extends self.ISpriteInstance {},
	HUD_Menu_Button: class extends self.ISpriteInstance {},
	HUD_Quest_Background: class extends self.ISpriteInstance {},
	Quest_Text: class extends self.ITextInstance {},
	Reward_Text: class extends self.ITextInstance {},
	Game_Boundary_Sprite: class extends self.ISpriteInstance {},
	Game_Upper_Boundary: class extends self.ISpriteInstance {},
	Menu_Play_Button: class extends self.ISpriteInstance {},
	HUD_Menu_Background: class extends self.ISpriteInstance {},
	Main_Menu_Button: class extends self.ISpriteInstance {},
	Settings_Menu_Button: class extends self.ISpriteInstance {},
	Settings_Menu: class extends self.ISpriteInstance {},
	Sound_Settings_Button: class extends self.ISpriteInstance {},
	Mute_Button: class extends self.ISpriteInstance {},
	Death_Screen: class extends self.ISpriteInstance {},
	Death_Keep_Inventory_Button: class extends self.ISpriteInstance {},
	Death_Dump_Inventory_Button2: class extends self.ISpriteInstance {},
	Shop_Explainer_Background: class extends self.ISpriteInstance {},
	Shop_Explainer_Text: class extends self.ITextInstance {},
	Shopkeeper_Sprite: class extends self.ISpriteInstance {},
	Item_Pick_Up_Text: class extends self.ITextInstance {},
	Warning_Text_Miner: class extends self.ITextInstance {},
	Sphere_Bullet_Sprite: class extends self.ISpriteInstance {},
	HUD_Upgrades_Button: class extends self.ISpriteInstance {},
	HUD_Money_Button: class extends self.ISpriteInstance {},
	HUD_Stats_Background_Black: class extends self.ISpriteInstance {},
	HUD_Stats_Text: class extends self.ITextInstance {},
	HUD_Credit_Card_Background: class extends self.ITiledBackgroundInstance {},
	Mitch: class extends self.ISpriteInstance {},
	Hell_Background: class extends self.ISpriteInstance {},
	Enemy_Turret_1: class extends self.ISpriteInstance {},
	Enemy_Body: class extends self.ISpriteInstance {},
	Enemy_Turret_2: class extends self.ISpriteInstance {},
	Enemy_Body2: class extends self.ISpriteInstance {},
	HUD_Enemy_1_HP_Background: class extends self.ISpriteInstance {},
	HUD_Enemy_1_HP_Bar: class extends self.ISpriteInstance {},
	HUD_Enemy_2_HP_Background: class extends self.ISpriteInstance {},
	HUD_Enemy_2_HP_Bar: class extends self.ISpriteInstance {},
	HUD_Enemy_1_HP_Text: class extends self.ITextInstance {},
	HUD_Enemy_2_HP_Text: class extends self.ITextInstance {},
	HUD_Devil_HP_Background2: class extends self.ISpriteInstance {},
	HUD_Devil_HP_Bar: class extends self.ISpriteInstance {},
	HUD_Devil_HP_Text: class extends self.ITextInstance {},
	Devil_Fire_Ring: class extends self.ISpriteInstance {},
	Mitch_Talk_Bubble: class extends self.ISpriteInstance {},
	HUD_Locked: class extends self.ISpriteInstance {},
	Gun_Crate: class extends self.ISpriteInstance {},
	Buy_Gun_Button: class extends self.ISpriteInstance {},
	Meta_Passive_Iron_Button: class extends self.ISpriteInstance {},
	Meta_Passive_Chromium_Button: class extends self.ISpriteInstance {},
	Meta_Passive_Copper_Button: class extends self.ISpriteInstance {},
	Render_Object: class extends self.ISpriteInstance {},
	Shop_Money_Text: class extends self.ITextInstance {},
	Meta_Engine_Upg_Button: class extends self.ISpriteInstance {},
	Meta_Engine_Effect_T1_Button: class extends self.ISpriteInstance {},
	Meta_Engine_Effect_Background: class extends self.ISpriteInstance {},
	Meta_Engine_Efficiency_Background: class extends self.ISpriteInstance {},
	Meta_Engine_Efficiency_T1_Button: class extends self.ISpriteInstance {},
	Meta_Shield_Upg_Button: class extends self.ISpriteInstance {},
	Meta_Shield_Impact_Background: class extends self.ISpriteInstance {},
	Meta_Shield_Impact_T1_Button: class extends self.ISpriteInstance {},
	Meta_Shield_Heat_Background: class extends self.ISpriteInstance {},
	Meta_Shield_Heat_T1_Button: class extends self.ISpriteInstance {},
	Enemy_Background_First: class extends self.ISpriteInstance {},
	Furnace_1_Background: class extends self.ITiledBackgroundInstance {},
	Furnace_1_Text: class extends self.ITextInstance {},
	Furnace_1_Buttons: class extends self.ITiledBackgroundInstance {},
	Enemies_Object: class extends self.ISpriteInstance {},
	Meta_Drill_DMG_Buttons: class extends self.ISpriteInstance {},
	Meta_Energy_Buttons: class extends self.ISpriteInstance {},
	Meta_Passive_Buttons: class extends self.ISpriteInstance {},
	Meta_All_Buttons: class extends self.ISpriteInstance {},
	Meta_Materials: class extends self.ISpriteInstance {},
	Meta_Engine_Buttons: class extends self.ISpriteInstance {},
	Meta_Shield_Buttons: class extends self.ISpriteInstance {},
	Sell_Items_Buttons: class extends self.ISpriteInstance {},
	Global_Inventory_Items_Text: class extends self.ITextInstance {},
	Deposit_Menu_Buttons: class extends self.ISpriteInstance {},
	Sell_Menu_Buttons: class extends self.ISpriteInstance {},
	Crates: class extends self.ISpriteInstance {},
	HUD_Menu_Buttons: class extends self.ISpriteInstance {},
	Settings_Menu_Buttons: class extends self.ISpriteInstance {},
	Death_Screen_All: class extends self.ISpriteInstance {},
	Dust_Animations: class extends self.ISpriteInstance {},
	Add_To_Cart_Text: class extends self.ITextInstance {},
	Mining_Blocks_Family: class extends self.ISpriteInstance {},
	Inventory_Sprites: class extends self.ISpriteInstance {},
	Global_Inventory_Text: class extends self.ITextInstance {},
	Ores: class extends self.ISpriteInstance {}
}